# Site settings
title: Patrick's Web Log
header-img: img/home-bg.png
email: patrick.eells@gmail.com
copyright_name: pi-track
description: > # this means to ignore newlines until "baseurl:"
  A blog about the things I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: patrickeells
github_username:  pi-track
learn_profile: pi-track
email_username: patrick.eells@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
